apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 172.17.0.2
          port: 22
        public:
          address: 10.8.131.81
          port: 22
    versions:
      controlPlane: 1.14.1
      kubelet: 1.14.1
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 172.17.0.3
          port: 22
        public:
          address: 10.8.131.82
          port: 22
    versions:
      controlPlane: 1.14.1
      kubelet: 1.14.1
kind: List
