apiVersion: apps/v1
kind: Deployment
metadata:
  name: fk-covid-net-inference
  namespace: kubeflow
  labels:
    app: fk-covid-net-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fk-covid-net-inference
  template:
    metadata:
      labels:
        app: fk-covid-net-inference
    spec:
      containers:
      - name: fk-covid-net-inference
        image: chanwit/fk-covid-net-inference
        ports:
        - containerPort: 5000
        env:
        - name: MINIO_ENDPOINT
          value: minio-service.kubeflow:9000
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KET
          value: minio123
        - name: MINIO_SSL
          value: "false"

# apiVersion: v1
# kind: Pod
# metadata:
#   name: secret-env-pod
# spec:
#   containers:
#   - name: mycontainer
#     image: redis
#     env:
#       - name: SECRET_USERNAME
#         valueFrom:
#           secretKeyRef:
#             name: mysecret
#             key: username
#       - name: SECRET_PASSWORD
#         valueFrom:
#           secretKeyRef:
#             name: mysecret
#             key: password
#   restartPolicy: Never